/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.ltdbth.gui;

/**
 *
 * @author Ian
 */
public class SystemToolsPage extends javax.swing.JFrame {

    /**
     * Creates new form SystemToolsPage
     */
    public SystemToolsPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButtonNinethRight = new javax.swing.JButton();
        jButtonNinethLeft = new javax.swing.JButton();
        jButtonEighthLeft = new javax.swing.JButton();
        jButtonEighthRight = new javax.swing.JButton();
        jButtonSeventhRight = new javax.swing.JButton();
        jButtonSeventhLeft = new javax.swing.JButton();
        jButtonSixthRight = new javax.swing.JButton();
        jButtonFifthRight = new javax.swing.JButton();
        jButtonFourthRight = new javax.swing.JButton();
        jButtonThirdRight = new javax.swing.JButton();
        JButtonSecondRight = new javax.swing.JButton();
        jButtonFirstRight = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButtonFirstLeft = new javax.swing.JButton();
        jButtonSecondLeft = new javax.swing.JButton();
        jButtonThirdLeft = new javax.swing.JButton();
        jButtonFourthLeft = new javax.swing.JButton();
        jButtonFifthLeft = new javax.swing.JButton();
        jButtonSixthLeft = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        DescriptionTextArea = new javax.swing.JTextArea();
        GoBackButton = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        jButton2.setText("jButton2");

        jButtonNinethRight.setText("jButton1");
        jButtonNinethRight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNinethRightActionPerformed(evt);
            }
        });

        jButtonNinethLeft.setText("jButton1");
        jButtonNinethLeft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNinethLeftActionPerformed(evt);
            }
        });

        jButtonEighthLeft.setText("jButton1");
        jButtonEighthLeft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEighthLeftActionPerformed(evt);
            }
        });

        jButtonEighthRight.setText("jButton1");
        jButtonEighthRight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEighthRightActionPerformed(evt);
            }
        });

        jButtonSeventhRight.setText("jButton1");
        jButtonSeventhRight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSeventhRightActionPerformed(evt);
            }
        });

        jButtonSeventhLeft.setText("jButton1");
        jButtonSeventhLeft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSeventhLeftActionPerformed(evt);
            }
        });

        jButtonSixthRight.setText("jButton1");
        jButtonSixthRight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSixthRightActionPerformed(evt);
            }
        });

        jButtonFifthRight.setText("jButton1");
        jButtonFifthRight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFifthRightActionPerformed(evt);
            }
        });

        jButtonFourthRight.setText("jButton1");
        jButtonFourthRight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFourthRightActionPerformed(evt);
            }
        });

        jButtonThirdRight.setText("jButton1");
        jButtonThirdRight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonThirdRightActionPerformed(evt);
            }
        });

        JButtonSecondRight.setText("jButton1");
        JButtonSecondRight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonSecondRightActionPerformed(evt);
            }
        });

        jButtonFirstRight.setText("jButton1");
        jButtonFirstRight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFirstRightActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 255));

        jPanel2.setBackground(new java.awt.Color(0, 153, 255));

        jLabel2.setFont(new java.awt.Font("Georgia", 1, 36)); // NOI18N
        jLabel2.setText("System Administration and Monitoring Tools");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(0, 153, 255));

        jButtonFirstLeft.setText("IP Config");
        jButtonFirstLeft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFirstLeftActionPerformed(evt);
            }
        });

        jButtonSecondLeft.setText("Malwarebytes");
        jButtonSecondLeft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSecondLeftActionPerformed(evt);
            }
        });

        jButtonThirdLeft.setText("VirusTotal");
        jButtonThirdLeft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonThirdLeftActionPerformed(evt);
            }
        });

        jButtonFourthLeft.setText("CCleaner");
        jButtonFourthLeft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFourthLeftActionPerformed(evt);
            }
        });

        jButtonFifthLeft.setText("Task Manager");
        jButtonFifthLeft.setMaximumSize(new java.awt.Dimension(50, 22));
        jButtonFifthLeft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFifthLeftActionPerformed(evt);
            }
        });

        jButtonSixthLeft.setText("Secure Password Generator");
        jButtonSixthLeft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSixthLeftActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonFirstLeft, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSecondLeft, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonThirdLeft, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonFourthLeft, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonFifthLeft, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSixthLeft, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 12, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jButtonFirstLeft, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonSecondLeft, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonThirdLeft, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jButtonFourthLeft, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jButtonFifthLeft, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonSixthLeft, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        DescriptionTextArea.setEditable(false);
        DescriptionTextArea.setColumns(20);
        DescriptionTextArea.setLineWrap(true);
        DescriptionTextArea.setRows(5);
        DescriptionTextArea.setWrapStyleWord(true);
        DescriptionTextArea.setAutoscrolls(false);
        DescriptionTextArea.setFocusable(false);
        DescriptionTextArea.setOpaque(false);
        jScrollPane1.setViewportView(DescriptionTextArea);

        GoBackButton.setText("Go Back");
        GoBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GoBackButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(GoBackButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(GoBackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15))
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonFirstLeftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFirstLeftActionPerformed
        new ipConfigPage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonFirstLeftActionPerformed

    private void jButtonSecondLeftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSecondLeftActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSecondLeftActionPerformed

    private void jButtonThirdLeftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonThirdLeftActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonThirdLeftActionPerformed

    private void jButtonFourthLeftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFourthLeftActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonFourthLeftActionPerformed

    private void jButtonFifthLeftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFifthLeftActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonFifthLeftActionPerformed

    private void jButtonSixthLeftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSixthLeftActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSixthLeftActionPerformed

    private void jButtonSeventhLeftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSeventhLeftActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSeventhLeftActionPerformed

    private void jButtonEighthLeftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEighthLeftActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonEighthLeftActionPerformed

    private void jButtonNinethLeftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNinethLeftActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonNinethLeftActionPerformed

    private void jButtonFirstRightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFirstRightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonFirstRightActionPerformed

    private void JButtonSecondRightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonSecondRightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JButtonSecondRightActionPerformed

    private void jButtonThirdRightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonThirdRightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonThirdRightActionPerformed

    private void jButtonFourthRightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFourthRightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonFourthRightActionPerformed

    private void jButtonFifthRightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFifthRightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonFifthRightActionPerformed

    private void jButtonSixthRightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSixthRightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSixthRightActionPerformed

    private void jButtonSeventhRightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSeventhRightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSeventhRightActionPerformed

    private void jButtonEighthRightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEighthRightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonEighthRightActionPerformed

    private void jButtonNinethRightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNinethRightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonNinethRightActionPerformed

    private void GoBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GoBackButtonActionPerformed
        new mainSplash().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_GoBackButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SystemToolsPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SystemToolsPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SystemToolsPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SystemToolsPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SystemToolsPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea DescriptionTextArea;
    private javax.swing.JButton GoBackButton;
    private javax.swing.JButton JButtonSecondRight;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonEighthLeft;
    private javax.swing.JButton jButtonEighthRight;
    private javax.swing.JButton jButtonFifthLeft;
    private javax.swing.JButton jButtonFifthRight;
    private javax.swing.JButton jButtonFirstLeft;
    private javax.swing.JButton jButtonFirstRight;
    private javax.swing.JButton jButtonFourthLeft;
    private javax.swing.JButton jButtonFourthRight;
    private javax.swing.JButton jButtonNinethLeft;
    private javax.swing.JButton jButtonNinethRight;
    private javax.swing.JButton jButtonSecondLeft;
    private javax.swing.JButton jButtonSeventhLeft;
    private javax.swing.JButton jButtonSeventhRight;
    private javax.swing.JButton jButtonSixthLeft;
    private javax.swing.JButton jButtonSixthRight;
    private javax.swing.JButton jButtonThirdLeft;
    private javax.swing.JButton jButtonThirdRight;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
